// API Configuration
export const API_BASE_URL = process.env.VITE_API_URL || 'http://localhost:3001';

// Default stake amount for betting calculations
export const DEFAULT_STAKE = 3000;

// Supported leagues for match parsing
export const SUPPORTED_LEAGUES = [
    'Premier League',
    'LaLiga',
    'Serie A',
    'Bundesliga',
    'Ligue 1',
    'Champions League',
    'Europa League',
    'World Cup'
];

// League keywords for auto-detection
export const LEAGUE_KEYWORDS = {
    'Premier League': ['arsenal', 'liverpool', 'manchester', 'chelsea', 'tottenham', 'brighton', 'newcastle', 'west ham'],
    'LaLiga': ['barcelona', 'real madrid', 'atletico', 'sevilla', 'valencia', 'villarreal', 'athletic', 'betis'],
    'Serie A': ['milan', 'inter', 'juventus', 'napoli', 'roma', 'lazio', 'fiorentina', 'atalanta'],
    'Bundesliga': ['bayern', 'dortmund', 'leipzig', 'leverkusen', 'frankfurt', 'wolfsburg', 'stuttgart', 'hoffenheim'],
    'Ligue 1': ['psg', 'paris', 'marseille', 'lyon', 'monaco', 'lille', 'lens', 'rennes'],
    'Champions League': ['champions', 'uefa', 'ucl'],
    'Europa League': ['europa', 'uel'],
    'World Cup': ['world cup', 'fifa']
};

// Team to country mapping for UEFA competitions
export const TEAM_COUNTRY_MAP = {
    'Real Madrid': '西班牙',
    'Barcelona': '西班牙',
    'Atletico Madrid': '西班牙',
    'Bayern Munich': '德国',
    'Borussia Dortmund': '德国',
    'Manchester City': '英格兰',
    'Manchester United': '英格兰',
    'Liverpool': '英格兰',
    'Chelsea': '英格兰',
    'Arsenal': '英格兰',
    'Tottenham': '英格兰',
    'PSG': '法国',
    'Paris Saint-Germain': '法国',
    'Marseille': '法国',
    'Lyon': '法国',
    'Monaco': '法国',
    'Inter Milan': '意大利',
    'AC Milan': '意大利',
    'Juventus': '意大利',
    'Napoli': '意大利',
    'Roma': '意大利',
    'Lazio': '意大利',
    'Atalanta': '意大利',
    'Porto': '葡萄牙',
    'Benfica': '葡萄牙',
    'Sporting': '葡萄牙',
    'Ajax': '荷兰',
    'PSV': '荷兰',
    'Feyenoord': '荷兰',
    'Galatasaray': '土耳其',
    'Fenerbahce': '土耳其',
    'Besiktas': '土耳其',
    'Panathinaikos': '希腊',
    'Olympiacos': '希腊',
    'PAOK': '希腊',
    'AEK Athens': '希腊',
    'Crvena Zvezda': '塞尔维亚',
    'Red Star Belgrade': '塞尔维亚',
    'Partizan': '塞尔维亚',
    'Viktoria Plzen': '捷克',
    'Sparta Prague': '捷克',
    'Slavia Prague': '捷克',
    'Ferencvarosi': '匈牙利',
    'Ludogorets': '保加利亚',
    'Dinamo Zagreb': '克罗地亚',
    'Hajduk Split': '克罗地亚',
    'Brann': '挪威',
    'Bodo/Glimt': '挪威',
    'Molde': '挪威',
    'Salzburg': '奥地利',
    'Sturm Graz': '奥地利',
    'Young Boys': '瑞士',
    'Basel': '瑞士',
    'Copenhagen': '丹麦',
    'Midtjylland': '丹麦',
    'Legia Warsaw': '波兰',
    'Malmo': '瑞典',
    'Shakhtar Donetsk': '乌克兰',
    'Dynamo Kyiv': '乌克兰',
    'FCSB': '罗马尼亚',
    'Genk': '比利时',
    'KRC Genk': '比利时',
    'Club Brugge': '比利时',
    'Anderlecht': '比利时',
    'Antwerp': '比利时',
    'Royal Antwerp': '比利时',
    'Gent': '比利时',
    'Union St.Gilloise': '比利时'
};

// OCR team name corrections (common OCR mistakes)
export const OCR_TEAM_CORRECTIONS = {
    'Manehester': 'Manchester',
    'Manchesler': 'Manchester',
    'Liverpoo!': 'Liverpool',
    'Liverpoo1': 'Liverpool',
    'Chelsca': 'Chelsea',
    'Arsena!': 'Arsenal',
    'Arsena1': 'Arsenal',
    'Tottenharn': 'Tottenham',
    'Bayem': 'Bayern',
    'Bayem Munich': 'Bayern Munich',
    'Bayem Munchen': 'Bayern Munich',
    'Rea!': 'Real',
    'Rea1': 'Real',
    'Barce!ona': 'Barcelona',
    'Barce1ona': 'Barcelona',
    'Juve': 'Juventus',
    'Juvc': 'Juventus',
    'lnter': 'Inter',
    'lnter Milan': 'Inter Milan',
    'Ml': 'AC',
    'AC Ml': 'AC Milan',
    'AC Mi': 'AC Milan',
    'PSC': 'PSG',
    'Atietico': 'Atletico',
    'Ath!etic': 'Athletic',
    'Ath1etic': 'Athletic',
    'Dortrnund': 'Dortmund',
    'Leipzlg': 'Leipzig',
    'RB Leipzlg': 'RB Leipzig',
    'Napo!i': 'Napoli',
    'Napo1i': 'Napoli',
    'Marse!lle': 'Marseille',
    'Marse1lle': 'Marseille'
};
